# IntelliJ repository (unofficial ppa: https://github.com/JonasGroeger/jetbrains-ppa)
- name: apt key for IntelliJ IDEA
  apt_key:
    url: https://s3.eu-central-1.amazonaws.com/jetbrains-ppa/0xA6E8698A.pub.asc
    state: present
    keyring: /etc/apt/trusted.gpg.d/jetbrains.gpg

- name: apt repo for IntelliJ IDEA
  apt_repository: repo='deb http://jetbrains-ppa.s3-website.eu-central-1.amazonaws.com any main' update_cache=yes

# IntelliJ IDEA community(~968mb installed in /opt/intellij-idea-community)
- name: install IntelliJ IDEs
  when: "'intellij-idea' in devtools"
  apt:
    state: present
    pkg:
    - intellij-idea-community

# For intellij+kotlin, we need to fetch kotlin from maven (it doesn't want to easily use the local files we have)
- name: install maven
  apt:
    pkg: maven
    state: present
- name: make sure m2 repository exists
  file:
    state: directory
    path: /opt/m2/repository
    mode: 0755
    owner: root
    group: root
# TODO: figure out where 1.9.22 comes from (intellij has a default for this)
# TODO: maybe from /opt/intellij-idea-community/plugins/Kotlin/kotlinc/build.txt
- name: fetch some things from maven
  shell: mvn dependency:get -Dartifact="org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.9.22" -Dmaven.repo.local="/opt/m2/repository"

# PyCharm Community(523mb installed in /opt/pycharm-community)
- name: install PyCharm
  when: "'intellij-pycharm' in devtools"
  apt:
    state: present
    pkg:
    - pycharm-community

# Clion(1028mb installed in /opt/clion)
- name: install clion
  when: "'intellij-clion' in devtools"
  block:
    - name: install clion
      apt:
        state: present
        pkg:
        - clion

    # Clion likes a weirdly formatted keyfile (UCS2 encoding with a BOM)
    - name: create a script to configure clion license
      copy:
        dest: /usr/local/bin/clion-license-key-install
        mode: 0755
        content: |
          #!/bin/bash
          mkdir -p $HOME/.config/JetBrains/CLion2023.3
          (
            printf '\xFF\xFF';
            echo -en "<certificate-key>\n{{ clion_license_key }}" | iconv -f UTF-8 -t UCS2 -
          ) > $HOME/.config/JetBrains/CLion2023.3/clion.key
      when: clion_license_key | length > 0

    - name: add licensekey script to autostart
      copy:
        dest: /etc/xdg/autostart/clion-license-key-install.desktop
        content: |
          [Desktop Entry]
          Type=Application
          Exec=/usr/local/bin/clion-license-key-install
          NoDisplay=true
      when: clion_license_key | length > 0

    - name: hide clion shortcut (if we don't have a license key for it)
      shell: mv /usr/share/applications/clion.desktop /usr/share/applications/clion.desktop.disabled
      args:
        creates: /usr/share/applications/clion.desktop.disabled
      when: clion_license_key | length == 0
