---
- name: install unzip so we can extract kotlin
  apt:
    pkg: unzip
    state: present
- name: install kotlin
  unarchive: src=files/kotlin-compiler-1.7.10.zip dest=/opt creates=/opt/kotlinc
- name: create symlinks for kotlin
  file:
    src: /opt/kotlinc/bin/{{ binary_name }}
    dest: /usr/local/bin/{{ binary_name }}
    state: link
  loop_control:
    loop_var: binary_name
  with_items:
    - kapt
    - kotlin
    - kotlinc
    - kotlinc-js
    - kotlinc-jvm
    - kotlin-dce-js

- name: kotlin docs
  when: not devdocs
  block:
    # kotlin pdf doc (single file)
    - name: create directory for kotlin docs
      file:
        state: directory
        mode: 0755
        path: /opt/kotlin-docs

    - name: fetch kotlin pdf
      get_url:
        url: https://kotlinlang.org/docs/kotlin-reference.pdf
        dest: /opt/kotlin-docs/kotlin-reference.pdf
        mode: 0644
    - ansible.utils.update_fact:
        updates:
          - path: "lang_docs['Kotlin']"
            value:
              name: Kotlin PDF
              id: kotlin
              path: /opt/kotlin-docs
              index: kotlin-reference.pdf
      register: updated
    - set_fact:
        lang_docs: "{{ updated.lang_docs }}"
