---
- name: scala
  apt:
    state: present
    pkg:
      - scala

# - name: scala docs
#   when: not devdocs
#   block:
#     - name: scala
#       apt:
#         state: present
#         pkg:
#           - scala-doc       # 413mb somehow
#     - ansible.utils.update_fact:
#         updates:
#           - path: "lang_docs['Scala']"
#             value:
#               name: Scala Documentation
#               id: scala
#               path: /usr/share/doc/scala-2.11/api/library
#               index: index.html
#       register: updated
#     - set_fact:
#         lang_docs: "{{ updated.lang_docs }}"
